version: '3.7'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres-max-scoring
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: max-scoring-development
      POSTGRES_DATA: .pgdata
    volumes:
      - ./data/postgres
# POSTGRES_DATA: /var/lib/postgresql/data/pgdata
